### ISSUE TITLE
OP's Cant Join!!!

### ISSUE THREAD

**Issue by ghost** [RealTesseract/Tesseract#2]
There is this major bug that is causing the OP's to not bypass and connect to server in whitelist!! Before the update everything was fine an OPs were able to connect to server in whitelist but after the update it would no longer let them connect. Plz fix the issue.

**Comment by RealTesseract** [comment]
Did you run the command in console whitelist add name because it's working perfectly for us.

**Comment by ghost** [comment]
Idk what it was but i reinstalled all my plugins, deleted and installed Tesseract.phar file again and now everything works. Thank you developers. Closing issue!!
