### ISSUE TITLE
Phar file plz.

### ISSUE THREAD

**Issue by ghost** [RealTesseract/Tesseract#3]
Please upload the v1.0.8 .phar file.

**Comment by RealTesseract** [comment]
I'll upload it in a little while I'm making some changes to some files

**Comment by ghost** [comment]
Okay

**Comment by RealTesseract** [comment]
Just uploaded the file click on Releases and click on the one that works for v1.0.8

**Comment by ghost** [comment]
Thanks. Can be closed.
